version: '3.8'

services:
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
       POSTGRES_DB: shop
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: 123123
    networks:
      - private_network
      - bridge_network
    volumes:
      - pgdata:/home/qwerty/Documents/volumes

  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - private_network
      - bridge_network
    volumes:
      - redisdata:/home/qwerty/Documents/volumes
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_NAME: shop
      DB_USER: admin
      DB_PASSWORD: 123123
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - private_network
      - bridge_network

networks:
  private_network:
    driver: bridge
  bridge_network:
    external: true

volumes:
  pgdata:
  redisdata:
